create table instruments (
    id              uuid primary key,
    symbol          varchar(20) not null unique,
    name            varchar(120) not null,
    exchange        varchar(10) not null,
    asset_class     varchar(10) not null,
    sector          varchar(40) not null,
    currency        varchar(3) not null,
    reference_price numeric(18, 4) not null,
    active          boolean not null default true
);

insert into instruments (id, symbol, name, exchange, asset_class, sector, currency, reference_price) values
    (gen_random_uuid(), 'RELIANCE', 'Reliance Industries', 'NSE', 'EQUITY', 'Energy', 'INR', 2875.00),
    (gen_random_uuid(), 'ONGC', 'Oil and Natural Gas Corporation', 'NSE', 'EQUITY', 'Energy', 'INR', 268.00),
    (gen_random_uuid(), 'BPCL', 'Bharat Petroleum', 'NSE', 'EQUITY', 'Energy', 'INR', 612.00),
    (gen_random_uuid(), 'IOC', 'Indian Oil Corporation', 'NSE', 'EQUITY', 'Energy', 'INR', 165.00),
    (gen_random_uuid(), 'TCS', 'Tata Consultancy Services', 'NSE', 'EQUITY', 'Technology', 'INR', 3910.00),
    (gen_random_uuid(), 'INFY', 'Infosys', 'NSE', 'EQUITY', 'Technology', 'INR', 1655.00),
    (gen_random_uuid(), 'WIPRO', 'Wipro', 'NSE', 'EQUITY', 'Technology', 'INR', 452.00),
    (gen_random_uuid(), 'HCLTECH', 'HCL Technologies', 'NSE', 'EQUITY', 'Technology', 'INR', 1490.00),
    (gen_random_uuid(), 'TECHM', 'Tech Mahindra', 'NSE', 'EQUITY', 'Technology', 'INR', 1330.00),
    (gen_random_uuid(), 'HDFCBANK', 'HDFC Bank', 'NSE', 'EQUITY', 'Financials', 'INR', 1685.00),
    (gen_random_uuid(), 'ICICIBANK', 'ICICI Bank', 'NSE', 'EQUITY', 'Financials', 'INR', 1145.00),
    (gen_random_uuid(), 'SBIN', 'State Bank of India', 'NSE', 'EQUITY', 'Financials', 'INR', 825.00),
    (gen_random_uuid(), 'KOTAKBANK', 'Kotak Mahindra Bank', 'NSE', 'EQUITY', 'Financials', 'INR', 1760.00),
    (gen_random_uuid(), 'AXISBANK', 'Axis Bank', 'NSE', 'EQUITY', 'Financials', 'INR', 1135.00),
    (gen_random_uuid(), 'BAJFINANCE', 'Bajaj Finance', 'NSE', 'EQUITY', 'Financials', 'INR', 7150.00),
    (gen_random_uuid(), 'HDFCLIFE', 'HDFC Life Insurance', 'NSE', 'EQUITY', 'Financials', 'INR', 630.00),
    (gen_random_uuid(), 'ITC', 'ITC', 'NSE', 'EQUITY', 'Consumer', 'INR', 445.00),
    (gen_random_uuid(), 'HINDUNILVR', 'Hindustan Unilever', 'NSE', 'EQUITY', 'Consumer', 'INR', 2480.00),
    (gen_random_uuid(), 'NESTLEIND', 'Nestle India', 'NSE', 'EQUITY', 'Consumer', 'INR', 2510.00),
    (gen_random_uuid(), 'BRITANNIA', 'Britannia Industries', 'NSE', 'EQUITY', 'Consumer', 'INR', 4880.00),
    (gen_random_uuid(), 'DABUR', 'Dabur India', 'NSE', 'EQUITY', 'Consumer', 'INR', 530.00),
    (gen_random_uuid(), 'TITAN', 'Titan Company', 'NSE', 'EQUITY', 'Consumer', 'INR', 3420.00),
    (gen_random_uuid(), 'SUNPHARMA', 'Sun Pharmaceutical', 'NSE', 'EQUITY', 'Healthcare', 'INR', 1620.00),
    (gen_random_uuid(), 'DRREDDY', 'Dr Reddys Laboratories', 'NSE', 'EQUITY', 'Healthcare', 'INR', 1290.00),
    (gen_random_uuid(), 'CIPLA', 'Cipla', 'NSE', 'EQUITY', 'Healthcare', 'INR', 1495.00),
    (gen_random_uuid(), 'APOLLOHOSP', 'Apollo Hospitals', 'NSE', 'EQUITY', 'Healthcare', 'INR', 6320.00),
    (gen_random_uuid(), 'DIVISLAB', 'Divis Laboratories', 'NSE', 'EQUITY', 'Healthcare', 'INR', 4110.00),
    (gen_random_uuid(), 'LT', 'Larsen and Toubro', 'NSE', 'EQUITY', 'Industrials', 'INR', 3560.00),
    (gen_random_uuid(), 'SIEMENS', 'Siemens', 'NSE', 'EQUITY', 'Industrials', 'INR', 7020.00),
    (gen_random_uuid(), 'ABB', 'ABB India', 'NSE', 'EQUITY', 'Industrials', 'INR', 6890.00),
    (gen_random_uuid(), 'TATASTEEL', 'Tata Steel', 'NSE', 'EQUITY', 'Materials', 'INR', 148.00),
    (gen_random_uuid(), 'JSWSTEEL', 'JSW Steel', 'NSE', 'EQUITY', 'Materials', 'INR', 905.00),
    (gen_random_uuid(), 'HINDALCO', 'Hindalco Industries', 'NSE', 'EQUITY', 'Materials', 'INR', 640.00),
    (gen_random_uuid(), 'ULTRACEMCO', 'UltraTech Cement', 'NSE', 'EQUITY', 'Materials', 'INR', 11200.00),
    (gen_random_uuid(), 'GRASIM', 'Grasim Industries', 'NSE', 'EQUITY', 'Materials', 'INR', 2480.00),
    (gen_random_uuid(), 'BHARTIARTL', 'Bharti Airtel', 'NSE', 'EQUITY', 'Telecom', 'INR', 1440.00),
    (gen_random_uuid(), 'NTPC', 'NTPC', 'NSE', 'EQUITY', 'Utilities', 'INR', 358.00),
    (gen_random_uuid(), 'POWERGRID', 'Power Grid Corporation', 'NSE', 'EQUITY', 'Utilities', 'INR', 322.00),
    (gen_random_uuid(), 'MARUTI', 'Maruti Suzuki India', 'NSE', 'EQUITY', 'Auto', 'INR', 12650.00),
    (gen_random_uuid(), 'TATAMOTORS', 'Tata Motors', 'NSE', 'EQUITY', 'Auto', 'INR', 985.00),
    (gen_random_uuid(), 'M&M', 'Mahindra and Mahindra', 'NSE', 'EQUITY', 'Auto', 'INR', 2870.00),
    (gen_random_uuid(), 'EICHERMOT', 'Eicher Motors', 'NSE', 'EQUITY', 'Auto', 'INR', 4790.00),
    (gen_random_uuid(), 'NIFTYBEES', 'Nippon India ETF Nifty 50 BeES', 'NSE', 'ETF', 'Index Fund', 'INR', 262.00),
    (gen_random_uuid(), 'BANKBEES', 'Nippon India ETF Nifty Bank BeES', 'NSE', 'ETF', 'Index Fund', 'INR', 492.00),
    (gen_random_uuid(), 'GOLDBEES', 'Nippon India ETF Gold BeES', 'NSE', 'ETF', 'Commodity', 'INR', 62.00),
    (gen_random_uuid(), 'NIFTY50', 'Nifty 50 Index', 'NSE', 'INDEX', 'Index', 'INR', 24150.00);
